/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-auto-import
export {}
declare global {
  const computed: typeof import('vue')['computed']
  const defineStore: typeof import('pinia')['defineStore']
  const ref: typeof import('vue')['ref']
  const terminal: typeof import('virtual:terminal')['terminal']
  const useMouse: typeof import('@vueuse/core')['useMouse']
}
